from __future__ import annotations

from typing import Protocol

import numpy as np

from app.domain.contracts import Keypoint, ModelMetadata, PersonBox, RawPose


class PoseModelAdapter(Protocol):
    @property
    def metadata(self) -> ModelMetadata: ...
    def load(self) -> None: ...
    def warm(self) -> None: ...
    def infer(self, image: np.ndarray) -> RawPose | None: ...


class KeypointNormalizer(Protocol):
    def normalize(self, raw: RawPose) -> tuple[list[Keypoint], PersonBox]: ...


class AvatarRenderer(Protocol):
    @property
    def id(self) -> str: ...
    def available(self) -> tuple[bool, str | None]: ...
    def render(self, image: np.ndarray, keypoints: list[Keypoint], edges: list[tuple[str, str]]) -> np.ndarray: ...


class MediaProcessor(Protocol):
    def decode_image(self, payload: bytes) -> np.ndarray: ...
    def encode_data_url(self, image: np.ndarray, quality: int = 88) -> str: ...
